### ISSUE TITLE
冰箱免root 不能启动双开

### ISSUE THREAD

**Issue by qlwz** [heruoxin/IceBox-SDK#1]
adb启动 
一加5T
应用双开初始化失败。
卸载冰箱后正常。

**Comment by heruoxin** [comment]
你好，
首先很抱歉此问题我无法解答，系统本身功能由手机厂商实现。
其次 GIthub Issues 是面对 SDK 而非冰箱本身的，之后冰箱自身问题请使用应用内功能渠道反馈。
