### ISSUE TITLE
island and icebox

### ISSUE THREAD

**Issue by ahhl** [heruoxin/IceBox-SDK#2]
i am using island and icebox together. i am facing a problem, if i do not use icebox for quite sometime, i will not able to unfreeze or freeze any app inside icebox. icebox will work again after i manually use island ( doing freeze/unfreeze inside island) then i go back to icebox to freeze and unfreeze.

**Comment by heruoxin** [comment]
Please use in-app feedback to post feedback about Ice Box app. The issues are about SDK.
