### ISSUE TITLE
你好，我之前购买过，请问怎么找回购买记录？

### ISSUE THREAD

**Issue by chainofhonor** [heruoxin/IceBox-SDK#3]
之前购买过 而且是买了2次
第一次是刚收到手机root了以后就购买了
第二次是刷了MIUI以后又够买了一次（同一部手机）
最近又把手机从miui刷回官方版本了，没有root用的adb命令

然后想开启完全功能，支付宝订单搜索icebox挨个月搜索但是没有搜索到，请问冰箱接收款项的账户能提供下吗 我搜索账户试试

**Comment by heruoxin** [comment]
请通过应用内反馈告诉我您的支付宝帐号，我来查询。
Github 是针对 SDK 的 issues，不是针对应用使用的。后续有其他问题请通过应用内反馈沟通。

**Comment by heruoxin** [comment]
应用使用问题请通过应用内反馈联系，这里是 SDK 的相关问题和讨论。
